import type { SessionInfoResponse } from '@booking/contracts';
import { Building2, ShieldCheck, Store } from 'lucide-react';
import { adminNavSections } from '~/routes/admin/nav';
import { partnerNavSections } from '~/routes/partner/nav';
import { tenantNavSections } from '~/routes/tenant/nav';
import type { DashboardArea, DashboardNavItem, DashboardNavSection } from './navigation-types';
import { dashboardPaths } from './paths';
import { firstPartnerMembership, firstTenantMembership } from './workspace';

export type { DashboardArea, DashboardNavItem, DashboardNavSection } from './navigation-types';

function flattenSections(sections: DashboardNavSection[]): DashboardNavItem[] {
  return sections.flatMap((section) => section.items);
}

const platformItems = flattenSections(adminNavSections);

/** Static area metadata. Scoped navigation is generated by dashboardAreasFor. */
export const DASHBOARD_AREAS: DashboardArea[] = [
  {
    scope: 'platform',
    title: 'Platform Admin',
    description: 'Quản trị nền tảng: tenant, gói dịch vụ, tài chính.',
    basePath: dashboardPaths.admin.home,
    icon: ShieldCheck,
    sections: adminNavSections,
    items: platformItems,
  },
  {
    scope: 'tenant',
    title: 'Tenant',
    description: 'Điều hành cửa hàng: listing, đặt chỗ, đối tác, khuyến mãi.',
    basePath: '/tenant',
    icon: Building2,
    sections: [],
    items: [],
  },
  {
    scope: 'partner',
    title: 'Partner',
    description: 'Quản lý dịch vụ, lịch trống và đơn đặt của bạn.',
    basePath: '/partner',
    icon: Store,
    sections: [],
    items: [],
  },
];

function visibleSections(
  sections: DashboardNavSection[],
  permissions: string[],
): DashboardNavSection[] {
  const held = new Set(permissions);

  return sections.flatMap((section) => {
    const items = section.items.filter((item) => !item.permission || held.has(item.permission));
    return items.length > 0 ? [{ ...section, items }] : [];
  });
}

function scopedArea(
  area: DashboardArea,
  sections: DashboardNavSection[],
  permissions: string[],
  overrides: Pick<DashboardArea, 'title' | 'basePath'>,
): DashboardArea {
  const visible = visibleSections(sections, permissions);
  return {
    ...area,
    ...overrides,
    sections: visible,
    items: flattenSections(visible),
  };
}

export function dashboardAreasFor(info: SessionInfoResponse, _pathname: string): DashboardArea[] {
  const areas: DashboardArea[] = [];
  const platform = info.scopes.find((membership) => membership.scope === 'platform');
  if (platform) {
    areas.push(
      scopedArea(DASHBOARD_AREAS[0]!, adminNavSections, platform.permissions, {
        title: DASHBOARD_AREAS[0]!.title,
        basePath: dashboardPaths.admin.home,
      }),
    );
  }

  const tenant = firstTenantMembership(info);
  if (tenant) {
    areas.push(
      scopedArea(DASHBOARD_AREAS[1]!, tenantNavSections, tenant.permissions, {
        title: tenant.tenantName ?? 'Tenant',
        basePath: dashboardPaths.tenant.home,
      }),
    );
  }

  const partner = firstPartnerMembership(info);
  if (partner) {
    areas.push(
      scopedArea(DASHBOARD_AREAS[2]!, partnerNavSections, partner.permissions, {
        title: partner.partnerName ?? 'Partner',
        basePath: dashboardPaths.partner.home,
      }),
    );
  }

  return areas;
}
