import { index, layout, route, type RouteConfig } from '@react-router/dev/routes';

export default [
  route('healthz', 'routes/healthz.ts'),
  route('uploads/presign', 'routes/uploads.presign.tsx'),
  route(':locale', 'routes/locale-layout.tsx', [
    index('routes/home.tsx'),
    route('t/:typeSlug', 'routes/catalog.tsx'),
    route('l/:listingSlug', 'routes/listing.tsx'),
    route('g/:groupSlug', 'routes/listing-group.tsx'),
    route('checkout', 'routes/checkout.tsx'),
    route('bookings', 'routes/bookings.tsx'),
    route('bookings/:code', 'routes/booking-detail.tsx'),
    layout('routes/auth/layout.tsx', [
      route('auth/login', 'routes/auth/login.tsx'),
      route('auth/logout', 'routes/auth/logout.tsx'),
      route('auth/register', 'routes/auth/register.tsx'),
      route('auth/register/verify', 'routes/auth/register-verify.tsx'),
      route('auth/register/password', 'routes/auth/register-password.tsx'),
      route('auth/register/success', 'routes/auth/register-success.tsx'),
      route('auth/forgot-password', 'routes/auth/forgot-password.tsx'),
      route('auth/forgot-password/verify', 'routes/auth/forgot-password-verify.tsx'),
      route('auth/forgot-password/new-password', 'routes/auth/forgot-password-new-password.tsx'),
      route('auth/forgot-password/success', 'routes/auth/forgot-password-success.tsx'),
    ]),
    layout('routes/_partner-layout.tsx', [
      route('become-partner', 'routes/partner-onboarding/layout.tsx', [
        index('routes/become-partner.tsx'),
        route('verify', 'routes/partner-onboarding/verify.tsx'),
        route('password', 'routes/partner-onboarding/password.tsx'),
        route('profile', 'routes/partner-onboarding/profile.tsx'),
        route('done', 'routes/partner-onboarding/done.tsx'),
      ]),
      route('become-affiliate', 'routes/become-affiliate.tsx'),
    ]),
  ]),
  index('routes/legacy/home.tsx'),
  route('t/:typeSlug', 'routes/legacy/catalog.tsx'),
  route('l/:listingSlug', 'routes/legacy/listing.tsx'),
  route('g/:groupSlug', 'routes/legacy/listing-group.tsx'),
  route('checkout', 'routes/legacy/checkout.tsx'),
  route('bookings', 'routes/legacy/bookings.tsx'),
  route('bookings/:code', 'routes/legacy/booking-detail.tsx'),
  route('become-partner', 'routes/legacy/become-partner.tsx'),
  route('become-affiliate', 'routes/legacy/become-affiliate.tsx'),
  route('set-locale', 'routes/set-locale.tsx'),
  route('sitemap.xml', 'routes/sitemap[.]xml.tsx'),
  route('robots.txt', 'routes/robots[.]txt.tsx'),
] satisfies RouteConfig;
