import type { ListingTypeIcon } from '@booking/contracts';

// Vietnamese labels for every lucide icon in the `LISTING_TYPE_ICONS` allowlist.
// Used by the shared IconPicker (listing-type icon + per-attribute icons) so the
// grid is searchable by meaning, not just by lucide name. Keys are exhaustive:
// the `Record<ListingTypeIcon, …>` type breaks the build if the allowlist grows
// without a label here.
export const ICON_LABEL: Record<ListingTypeIcon, string> = {
  // Studio / media
  Camera: 'Máy ảnh',
  Aperture: 'Khẩu độ',
  Video: 'Quay phim',
  Clapperboard: 'Clapperboard',
  Projector: 'Máy chiếu',
  Mic: 'Micro',
  Music: 'Âm nhạc',
  Speaker: 'Loa',
  Lightbulb: 'Ánh sáng',
  // Space / stay
  Building2: 'Toà nhà',
  House: 'Nhà',
  Hotel: 'Khách sạn',
  BedDouble: 'Giường',
  DoorOpen: 'Cửa/Phòng',
  Warehouse: 'Kho',
  Store: 'Cửa hàng',
  Armchair: 'Ghế',
  Sofa: 'Sofa',
  Bath: 'Phòng tắm',
  Landmark: 'Địa danh',
  // Transport
  Car: 'Ô tô',
  Bike: 'Xe đạp',
  Ship: 'Tàu thuyền',
  Plane: 'Máy bay',
  // Sport / wellness
  Dumbbell: 'Tập luyện',
  Trophy: 'Cúp',
  Waves: 'Bơi/Sóng',
  HeartPulse: 'Sức khoẻ',
  Stethoscope: 'Y tế',
  Footprints: 'Bước chân',
  // Beauty / fashion
  Palette: 'Bảng màu',
  Scissors: 'Làm tóc',
  Sparkles: 'Trang điểm',
  Brush: 'Cọ vẽ',
  Shirt: 'Trang phục',
  Flower2: 'Hoa',
  // Learning / events
  GraduationCap: 'Tốt nghiệp',
  BookOpen: 'Sách',
  Users: 'Nhóm/Thợ',
  Drama: 'Sân khấu',
  PartyPopper: 'Tiệc',
  Cake: 'Bánh',
  Utensils: 'Ăn uống',
  Coffee: 'Cà phê',
  // Outdoors
  Tent: 'Lều/Cắm trại',
  TreePine: 'Cây/Ngoại cảnh',
  MapPin: 'Địa điểm',
  // Equipment / misc
  Package: 'Gói/Kiện',
  Boxes: 'Thùng',
  Wrench: 'Dụng cụ',
  Laptop: 'Laptop',
  Monitor: 'Màn hình',
  Gamepad2: 'Trò chơi',
  Baby: 'Em bé',
  Dog: 'Thú cưng',
  CalendarDays: 'Lịch',
  Clock: 'Thời gian',
  Tag: 'Nhãn',
  // Attribute / spec-card glyphs
  Gift: 'Ưu đãi/Quà tặng',
  Images: 'Ảnh/Hậu kì',
  CircleSlash: 'Không bao gồm',
  Star: 'Nổi bật',
  Info: 'Thông tin',
  Check: 'Bao gồm',
  // Amenities / in-space utilities
  Wifi: 'Wi-Fi',
  Bluetooth: 'Bluetooth',
  AirVent: 'Máy lạnh',
  Fan: 'Quạt',
  Snowflake: 'Điều hoà/Lạnh',
  Thermometer: 'Nhiệt độ',
  Flame: 'Bếp/Lửa',
  WashingMachine: 'Máy giặt',
  Refrigerator: 'Tủ lạnh',
  Microwave: 'Lò vi sóng',
  Tv: 'Tivi',
  ShowerHead: 'Vòi sen',
  Bed: 'Giường',
  Cctv: 'Camera an ninh',
  Lock: 'Khoá',
  KeyRound: 'Chìa khoá',
  Bell: 'Chuông/Lễ tân',
  Cigarette: 'Được hút thuốc',
  CigaretteOff: 'Cấm hút thuốc',
  Accessibility: 'Lối cho xe lăn',
  Plug: 'Ổ cắm điện',
  PlugZap: 'Sạc nhanh',
  Zap: 'Điện',
  LampDesk: 'Đèn bàn',
  Battery: 'Pin',
  BatteryCharging: 'Sạc pin',
  Flashlight: 'Đèn pin',
  Droplet: 'Nước',
  Droplets: 'Nước/Độ ẩm',
  // Food & drink
  CookingPot: 'Nấu ăn',
  ChefHat: 'Đầu bếp',
  Wine: 'Rượu vang',
  Beer: 'Bia',
  Pizza: 'Pizza',
  IceCreamCone: 'Kem',
  Croissant: 'Bánh ngọt',
  Soup: 'Món súp',
  Salad: 'Salad',
  Popcorn: 'Bắp rang',
  Cookie: 'Bánh quy',
  UtensilsCrossed: 'Nhà hàng',
  // Nature / weather / outdoors
  Sun: 'Nắng/Ban ngày',
  Moon: 'Ban đêm',
  Umbrella: 'Ô/Dù',
  Wind: 'Gió',
  Leaf: 'Cây xanh',
  Trees: 'Rừng cây',
  Mountain: 'Núi',
  MountainSnow: 'Núi tuyết',
  Sunrise: 'Bình minh',
  Sunset: 'Hoàng hôn',
  TreePalm: 'Bãi biển/Nhiệt đới',
  // Transport
  Bus: 'Xe buýt',
  Train: 'Tàu hoả',
  TramFront: 'Tàu điện',
  Truck: 'Xe tải',
  Caravan: 'Xe cắm trại',
  Fuel: 'Trạm xăng',
  Sailboat: 'Thuyền buồm',
  Anchor: 'Neo/Bến',
  Navigation: 'Chỉ đường',
  Compass: 'La bàn',
  Map: 'Bản đồ',
  MapPinned: 'Vị trí ghim',
  Route: 'Lộ trình',
  // Beauty / fashion / lifestyle
  Gem: 'Trang sức',
  Crown: 'Cao cấp/VIP',
  Glasses: 'Kính',
  Watch: 'Đồng hồ',
  ShoppingBag: 'Túi mua sắm',
  Smile: 'Nụ cười',
  Hand: 'Bàn tay',
  HandHeart: 'Tận tâm',
  Flower: 'Hoa',
  // Events / media / audio
  Ticket: 'Vé',
  Headphones: 'Tai nghe',
  Guitar: 'Guitar',
  Piano: 'Piano',
  Drum: 'Trống',
  Radio: 'Radio',
  Disc: 'Đĩa nhạc',
  Film: 'Phim',
  Presentation: 'Trình chiếu',
  Volume2: 'Âm lượng',
  // Kids / pets
  Cat: 'Mèo',
  Bird: 'Chim',
  Fish: 'Cá',
  Rabbit: 'Thỏ',
  PawPrint: 'Thú cưng',
  // Sports / wellness
  Medal: 'Huy chương',
  Award: 'Giải thưởng',
  Target: 'Mục tiêu',
  Backpack: 'Ba lô',
  // Tools / tech
  Hammer: 'Búa',
  Ruler: 'Thước đo',
  PaintBucket: 'Sơn',
  PaintRoller: 'Con lăn sơn',
  Pen: 'Bút',
  Pencil: 'Bút chì',
  Briefcase: 'Cặp/Công việc',
  Smartphone: 'Điện thoại',
  Tablet: 'Máy tính bảng',
  Printer: 'Máy in',
  Cpu: 'Vi xử lý',
  Keyboard: 'Bàn phím',
  Mouse: 'Chuột',
  Webcam: 'Webcam',
  Server: 'Máy chủ',
  // Commerce / trust
  ShoppingCart: 'Giỏ hàng',
  CreditCard: 'Thẻ',
  Wallet: 'Ví',
  Banknote: 'Tiền mặt',
  Coins: 'Xu/Tiền',
  Percent: 'Giảm giá',
  Tags: 'Nhãn giá',
  Receipt: 'Hoá đơn',
  ShieldCheck: 'Bảo đảm',
  Shield: 'Bảo vệ',
  BadgeCheck: 'Đã xác minh',
  Key: 'Chìa khoá',
  Timer: 'Hẹn giờ',
  Hourglass: 'Thời lượng',
  Heart: 'Yêu thích',
  ThumbsUp: 'Đánh giá tốt',
  // Contact / people / general
  Phone: 'Điện thoại',
  PhoneCall: 'Gọi điện',
  Mail: 'Email',
  MessageCircle: 'Nhắn tin',
  Send: 'Gửi',
  Globe: 'Website',
  HelpCircle: 'Trợ giúp',
  User: 'Người dùng',
  UserRound: 'Cá nhân',
  UserCheck: 'Đã xác nhận',
};

/** The picker's ordered option list: every allowlisted icon with its label. */
export const ICON_OPTIONS: { name: ListingTypeIcon; label: string }[] = (
  Object.entries(ICON_LABEL) as [ListingTypeIcon, string][]
).map(([name, label]) => ({ name, label }));
